/* Psychedelia - Feedback Loop (Shadertoy pass graph)
 * Video feedback: each frame re-samples the previous one through a small
 * transform, fades it and adds a source pattern. "Flow Speed" scales the
 * feedback steps independently of the source animation and of the frame
 * rate, so trails can be slowed down without touching the sources.
 */
(function() {
    'use strict';

    var L = ShadertoyEffectRunner.lines;
    var pass = ShadertoyEffectRunner.pass;

    function project() {
        var common = L([
            'uniform float u_zoom;',
            'uniform float u_rotation;',
            'uniform float u_color_shift;',
            'uniform float u_decay;',
            'uniform float u_source_pattern;',
            'uniform float u_source_strength;',
            'uniform float u_source_speed;',
            'uniform float u_flow_speed;',
            'uniform float u_transform_mode;',
            'uniform float u_warp;',
            'uniform float u_hue_drift;',
            'uniform float u_blend_mode;',
            'uniform float u_source_palette;',
            'uniform float u_seed;',
            'uniform vec4 u_seed_vec;',
            '',
            'float hash21(vec2 p) {',
            '    p += u_seed_vec.xy * 41.0 + u_seed;',
            '    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);',
            '}',
            '',
            'mat2 rot2(float a) {',
            '    float c = cos(a);',
            '    float s = sin(a);',
            '    return mat2(c, -s, s, c);',
            '}',
            '',
            'vec3 cosPal(float t, vec3 a, vec3 b, vec3 c, vec3 d) {',
            '    return a + b * cos(6.28318 * (c * t + d));',
            '}',
            '',
            '// Source palettes',
            'vec3 rainbow(float t) {',
            '    float p = floor(u_source_palette + 0.5);',
            '    if (p < 0.5) return 0.5 + 0.5 * cos(6.28318 * (t + vec3(0.0, 0.33, 0.67)));',
            '    if (p < 1.5) return cosPal(t, vec3(0.5), vec3(0.5), vec3(1.0), vec3(0.0, 0.1, 0.2));',
            '    if (p < 2.5) return cosPal(t, vec3(0.5, 0.2, 0.05), vec3(0.5, 0.35, 0.15), vec3(1.0, 0.8, 0.6), vec3(0.0, 0.12, 0.2));',
            '    if (p < 3.5) return cosPal(t, vec3(0.2, 0.45, 0.6), vec3(0.2, 0.35, 0.4), vec3(0.8, 0.9, 1.0), vec3(0.55, 0.6, 0.65));',
            '    if (p < 4.5) return cosPal(t, vec3(0.5), vec3(0.5), vec3(2.0, 1.0, 0.0), vec3(0.5, 0.2, 0.25));',
            '    if (p < 5.5) return cosPal(t, vec3(0.75), vec3(0.25), vec3(1.0), vec3(0.0, 0.33, 0.67));',
            '    if (p < 6.5) return cosPal(t, vec3(0.6, 0.3, 0.35), vec3(0.4, 0.3, 0.3), vec3(1.0, 1.0, 0.6), vec3(0.0, 0.15, 0.4));',
            '    return vec3(0.55 + 0.45 * cos(6.28318 * t));',
            '}',
            '',
            '// Rotate hue around the grey axis (feedback colour drift).',
            'vec3 hueRotate(vec3 c, float a) {',
            '    vec3 k = vec3(0.57735);',
            '    float ca = cos(a);',
            '    return c * ca + cross(k, c) * sin(a) + k * dot(k, c) * (1.0 - ca);',
            '}',
            '',
            'vec3 sourcePattern(vec2 uv, float t) {',
            '    float pattern = floor(u_source_pattern + 0.5);',
            '    if (pattern < 0.5) {',
            '        float v = sin(uv.x * 8.0 + t) + sin(uv.y * 6.0 + t * 0.7) + sin(length(uv - 0.5) * 10.0 - t);',
            '        return rainbow(v * 0.15 + t * 0.05) * u_source_strength;',
            '    }',
            '    if (pattern < 1.5) {',
            '        vec2 g = floor(uv * 72.0);',
            '        float n = hash21(g + floor(t * 6.0));',
            '        return rainbow(n + t * 0.05) * step(0.78, n) * u_source_strength;',
            '    }',
            '    if (pattern < 2.5) {',
            '        float d = length(uv - 0.5);',
            '        float v = sin(d * 32.0 - t * 3.0) * 0.5 + 0.5;',
            '        return rainbow(v + t * 0.1) * smoothstep(0.4, 1.0, v) * u_source_strength;',
            '    }',
            '    if (pattern < 3.5) {',
            '        vec2 gv = fract(uv * 9.0) - 0.5;',
            '        vec2 id = floor(uv * 9.0);',
            '        float d = length(gv);',
            '        float v = smoothstep(0.22, 0.08, d);',
            '        return rainbow(hash21(id) + t * 0.1) * v * u_source_strength;',
            '    }',
            '    if (pattern < 4.5) {',
            '        vec2 c = uv - 0.5;',
            '        float a = atan(c.y, c.x);',
            '        float r = length(c);',
            '        float v = sin(a * 5.0 + r * 24.0 - t * 3.0) * 0.5 + 0.5;',
            '        return rainbow(v + t * 0.05) * smoothstep(0.35, 1.0, v) * u_source_strength;',
            '    }',
            '    if (pattern < 5.5) {',
            '        vec2 c = uv - 0.5;',
            '        float best = 8.0;',
            '        for (int i = 0; i < 52; i++) {',
            '            float s = float(i) / 52.0 * 6.28318530718;',
            '            vec2 p = vec2(sin(3.0 * s + t), sin(4.0 * s + t * 0.73 + 1.5708)) * 0.36;',
            '            best = min(best, length(c - p));',
            '        }',
            '        float line = smoothstep(0.035, 0.004, best);',
            '        float glow = min(0.055 / (best + 0.002), 1.0);',
            '        return rainbow(t * 0.05 + best * 3.0) * (line + glow * 0.28) * u_source_strength;',
            '    }',
            '    if (pattern < 6.5) {',
            '        vec2 q = uv * 8.0;',
            '        vec2 cell = floor(q);',
            '        vec2 f = fract(q);',
            '        float nearest = 9.0;',
            '        float second = 9.0;',
            '        vec2 idKeep = vec2(0.0);',
            '        for (int y = -1; y <= 1; y++) {',
            '            for (int x = -1; x <= 1; x++) {',
            '                vec2 g = vec2(float(x), float(y));',
            '                vec2 id = cell + g;',
            '                vec2 rnd = vec2(hash21(id), hash21(id + 19.37));',
            '                vec2 site = g + rnd - f + sin(rnd * 6.28318 + t + id.yx) * 0.22;',
            '                float d = length(site);',
            '                if (d < nearest) { second = nearest; nearest = d; idKeep = id; }',
            '                else if (d < second) second = d;',
            '            }',
            '        }',
            '        float edge = exp(-abs(second - nearest) * 16.0);',
            '        float body = smoothstep(0.95, 0.08, nearest);',
            '        return rainbow(hash21(idKeep) + t * 0.04) * (body * 0.55 + edge) * u_source_strength;',
            '    }',
            '    if (pattern < 7.5) {',
            '        vec2 c = uv - 0.5;',
            '        float r = length(c);',
            '        float a = atan(c.y, c.x) + t * 0.18;',
            '        float sector = 6.28318530718 / 8.0;',
            '        a = abs(mod(a + sector * 0.5, sector) - sector * 0.5);',
            '        vec2 p = vec2(cos(a), sin(a)) * r;',
            '        float v = sin(p.x * 22.0 + t) * sin(p.y * 18.0 - t * 0.8);',
            '        float shards = smoothstep(0.50, 1.0, abs(v));',
            '        return rainbow(v * 0.2 + r + t * 0.05) * shards * u_source_strength;',
            '    }',
            '    if (pattern < 8.5) {',
            '        vec2 c = uv - 0.5;',
            '        float a = atan(c.y, c.x);',
            '        float r = length(c);',
            '        float flow = sin(c.x * 17.0 + sin(c.y * 7.0 + t) * 2.0 + t) * sin(c.y * 19.0 - t * 0.63);',
            '        float ribbons = smoothstep(0.72, 1.0, abs(flow)) * (0.45 + 0.55 * smoothstep(0.70, 0.0, r));',
            '        return rainbow(a * 0.15915 + flow * 0.18 + t * 0.05) * ribbons * u_source_strength;',
            '    }',
            '    if (pattern < 9.5) {',
            '        // Mandala bloom: petals around the centre.',
            '        vec2 c = uv - 0.5;',
            '        float r = length(c);',
            '        float a = atan(c.y, c.x);',
            '        float petals = abs(cos(a * 6.0 + sin(t) * 0.6)) * 0.18 + 0.05;',
            '        float ring = smoothstep(0.012, 0.0, abs(r - petals - 0.04 * sin(t * 1.3)));',
            '        float core = smoothstep(0.05, 0.0, r);',
            '        return rainbow(a * 0.0796 + t * 0.06) * (ring + core * 0.6) * u_source_strength * 1.6;',
            '    }',
            '    if (pattern < 10.5) {',
            '        // Starburst rays flashing outward.',
            '        vec2 c = uv - 0.5;',
            '        float a = atan(c.y, c.x);',
            '        float r = length(c);',
            '        float rays = pow(abs(sin(a * 9.0 + t * 0.7)), 24.0);',
            '        float pulse = smoothstep(0.02, 0.0, abs(r - fract(t * 0.35) * 0.45));',
            '        return rainbow(r * 2.0 + t * 0.08) * (rays * smoothstep(0.45, 0.0, r) + pulse) * u_source_strength * 3.0;',
            '    }',
            '    if (pattern < 11.5) {',
            '        // A flickering Julia set outline.',
            '        vec2 z = (uv - 0.5) * vec2(2.6, 2.6);',
            '        vec2 jc = vec2(-0.75 + 0.12 * cos(t * 0.31), 0.12 + 0.12 * sin(t * 0.27));',
            '        float it = 0.0;',
            '        for (int i = 0; i < 48; i++) {',
            '            z = vec2(z.x * z.x - z.y * z.y, 2.0 * z.x * z.y) + jc;',
            '            if (dot(z, z) > 16.0) break;',
            '            it += 1.0;',
            '        }',
            '        float edge = smoothstep(5.0, 16.0, it) * (1.0 - step(47.5, it));',
            '        return rainbow(it * 0.03 + t * 0.05) * edge * u_source_strength * 3.5;',
            '    }',
            '    if (pattern < 12.5) {',
            '        // Hex lattice outlines.',
            '        vec2 p = (uv - 0.5) * 9.0;',
            '        vec2 r = vec2(1.0, 1.7320508);',
            '        vec2 h = r * 0.5;',
            '        vec2 a = mod(p, r) - h;',
            '        vec2 b = mod(p - h, r) - h;',
            '        vec2 g = dot(a, a) < dot(b, b) ? a : b;',
            '        vec2 q = abs(g);',
            '        float d = 0.5 - max(dot(q, normalize(vec2(1.0, 1.7320508))), q.x);',
            '        float line = smoothstep(0.06, 0.0, d);',
            '        return rainbow(length(p) * 0.05 - t * 0.08) * line * (0.6 + 0.4 * sin(t + length(p))) * u_source_strength * 2.0;',
            '    }',
            '    if (pattern < 13.5) {',
            '        // Orbiting orbs.',
            '        vec2 c = uv - 0.5;',
            '        vec3 col = vec3(0.0);',
            '        for (int i = 0; i < 7; i++) {',
            '            float fi = float(i);',
            '            vec2 p = vec2(cos(t * (0.6 + fi * 0.13) + fi * 0.9), sin(t * (0.5 + fi * 0.11) + fi * 1.7)) * (0.12 + fi * 0.035);',
            '            float d = length(c - p);',
            '            col += rainbow(fi * 0.14 + t * 0.04) * smoothstep(0.025, 0.0, d);',
            '        }',
            '        return col * u_source_strength * 4.5;',
            '    }',
            '    // Plasma worms: thin bright contour lines of a moving plasma.',
            '    vec2 p = uv * 6.0;',
            '    float v = sin(p.x + t) + sin(p.y * 1.3 - t * 0.8) + sin((p.x + p.y) * 0.7 + t * 0.5) + sin(length(p - 3.0) * 1.4 - t);',
            '    float worm = smoothstep(0.08, 0.0, abs(fract(v * 0.6) - 0.5));',
            '    return rainbow(v * 0.1 + t * 0.05) * worm * u_source_strength * 2.5;',
            '}'
        ]);

        var bufferA = L([
            'void mainImage(out vec4 fragColor, in vec2 fragCoord) {',
            '    vec2 uv = fragCoord / iResolution.xy;',
            '    vec2 center = vec2(0.5);',
            '    if (iMouse.z > 0.0) center = iMouse.xy / iResolution.xy;',
            '',
            '    // Feedback steps this frame: flow speed x frame time (60 fps = 1).',
            '    float steps = max(u_flow_speed, 0.0) * clamp(iTimeDelta * 60.0, 0.25, 4.0);',
            '    float zoomStep = pow(max(u_zoom, 0.0001), steps);',
            '    float rotStep = u_rotation * steps;',
            '    float mode = floor(u_transform_mode + 0.5);',
            '    float aspect = iResolution.x / max(iResolution.y, 1.0);',
            '',
            '    vec2 d = uv - center;',
            '    d.x *= aspect;',
            '    if (mode < 0.5) {',
            '        d = rot2(rotStep) * d * zoomStep;',
            '    } else if (mode < 1.5) {',
            '        float swirl = rotStep + u_warp * 0.05 * steps / (0.12 + length(d));',
            '        d = rot2(swirl) * d * zoomStep;',
            '    } else if (mode < 2.5) {',
            '        d = rot2(rotStep) * d * zoomStep;',
            '        float segs = 3.0 + floor(u_warp * 9.0);',
            '        float a = atan(d.y, d.x);',
            '        float sector = 6.28318530718 / segs;',
            '        a = abs(mod(a + sector * 0.5, sector) - sector * 0.5);',
            '        d = vec2(cos(a), sin(a)) * length(d);',
            '    } else if (mode < 3.5) {',
            '        float r = length(d);',
            '        float ripple = 1.0 + u_warp * 0.02 * steps * sin(r * 34.0 - iTime * 2.4);',
            '        d = rot2(rotStep) * d * zoomStep * ripple;',
            '    } else if (mode < 4.5) {',
            '        float r = length(d);',
            '        d = rot2(rotStep) * d * mix(zoomStep, zoomStep * zoomStep, clamp(r * 1.6, 0.0, 1.0));',
            '        d.y += u_warp * 0.004 * steps;',
            '    } else {',
            '        d.x = abs(d.x);',
            '        d = rot2(rotStep) * d * zoomStep;',
            '    }',
            '    d.x /= aspect;',
            '    vec2 fbUv = center + d;',
            '',
            '    float shift = u_color_shift * 0.01 * steps;',
            '    vec3 feedback;',
            '    feedback.r = texture(iChannel0, fbUv + vec2( shift, 0.0)).r;',
            '    feedback.g = texture(iChannel0, fbUv).g;',
            '    feedback.b = texture(iChannel0, fbUv - vec2( shift, 0.0)).b;',
            '    if (abs(u_hue_drift) > 0.0001) feedback = max(hueRotate(feedback, u_hue_drift * steps * 6.28318), 0.0);',
            '    feedback *= pow(clamp(u_decay, 0.0, 1.0), steps);',
            '    vec3 source = sourcePattern(uv, iTime * max(u_source_speed, 0.02));',
            '    float blend = floor(u_blend_mode + 0.5);',
            '    vec3 outCol;',
            '    if (blend < 0.5) outCol = feedback + source;',
            '    else if (blend < 1.5) outCol = 1.0 - (1.0 - feedback) * (1.0 - clamp(source, 0.0, 1.0));',
            '    else outCol = max(feedback, source);',
            '    fragColor = vec4(clamp(outCol, 0.0, 1.0), 1.0);',
            '}'
        ]);

        var image = L([
            'void mainImage(out vec4 fragColor, in vec2 fragCoord) {',
            '    vec3 color = texture(iChannel0, fragCoord / iResolution.xy).rgb;',
            '    fragColor = vec4(pow(color, vec3(0.9)), 1.0);',
            '}'
        ]);

        var p = ShadertoyPassGraph.makeDefaultProject(image);
        p.name = 'Feedback Loop';
        p.description = 'Stateful video-feedback transform using Buffer A ping-pong history.';
        p.common.source = common;
        pass(p, 'bufferA').enabled = true;
        pass(p, 'bufferA').source = bufferA;
        pass(p, 'bufferA').channels[0] = { slot: 0, kind: 'self', sourceId: 'bufferA', sampler: { filter: 'linear', wrap: 'clamp' } };
        pass(p, 'image').channels[0] = { slot: 0, kind: 'buffer', sourceId: 'bufferA', sampler: { filter: 'linear', wrap: 'clamp' } };
        return p;
    }

    var runner = ShadertoyEffectRunner.make({
        project: project
    });

    EffectRegistry.register({
        name: 'feedback',
        label: 'Feedback Loop',
        category: 'Distortion',
        description: 'Video feedback trails: sources stream through zoom, swirl, kaleido, ripple or tunnel transforms with independent flow speed',
        params: [
            { name: 'source_pattern', label: 'Source', type: 'select', options: ['Plasma', 'Noise', 'Rings', 'Dots', 'Spiral', 'Lissajous', 'Voronoi Cells', 'Kaleido Shards', 'Flow Ribbons', 'Mandala Bloom', 'Starburst Rays', 'Julia Flicker', 'Hex Lattice', 'Orbiting Orbs', 'Plasma Worms'], default: 0 },
            { name: 'source_palette', label: 'Source Colors', type: 'select', options: ['Rainbow', 'Neon', 'Fire', 'Ice', 'Acid', 'Pastel', 'Sunset', 'Mono'], default: 0 },
            { name: 'source_speed', label: 'Source Speed', min: 0.02, max: 3, default: 0.55, step: 0.02 },
            { name: 'source_strength', label: 'Source Strength', min: 0, max: 0.3, default: 0.08, step: 0.01 },
            { name: 'transform_mode', label: 'Transform', type: 'select', options: ['Zoom & Rotate', 'Swirl Vortex', 'Kaleido Mirror', 'Ripple Lens', 'Tunnel Drift', 'Mirror Split'], default: 0 },
            { name: 'flow_speed', label: 'Flow Speed', min: 0.05, max: 3, default: 1, step: 0.05 },
            { name: 'zoom', label: 'Zoom', min: 0.95, max: 1.05, default: 0.98, step: 0.002 },
            { name: 'rotation', label: 'Rotation', min: -0.1, max: 0.1, default: 0.02, step: 0.005 },
            { name: 'warp', label: 'Warp Amount', min: 0, max: 1, default: 0.4, step: 0.02 },
            { name: 'decay', label: 'Trail Length', min: 0.9, max: 1, default: 0.97, step: 0.005 },
            { name: 'color_shift', label: 'Color Shift', min: 0, max: 0.1, default: 0.02, step: 0.005 },
            { name: 'hue_drift', label: 'Hue Drift', min: -0.02, max: 0.02, default: 0, step: 0.001 },
            { name: 'blend_mode', label: 'Blend', type: 'select', options: ['Add', 'Screen', 'Lighten'], default: 0 }
        ],
        _usesShadertoyGraph: true,
        init: runner.init,
        cleanup: runner.cleanup,
        render: runner.render,
        resetSimulation: runner.reset,
        getDiagnostics: runner.getDiagnostics
    });
})();
